version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus

#    networks:
#      - local



  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    depends_on:
      - prometheus
#    networks:
#      - internal
    volumes:
      - grafana-storage:/var/lib/grafana



  postgres:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_DB=aia_perf1
      - POSTGRES_PASSWORD=Postgres01
      - POSTGRES_USER=postgres
      - TZ=Europe/Kiev
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    command:
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
      -c log_min_error_statement=error
      -c log_autovacuum_min_duration=0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G



volumes:
  postgres_data:
  postgres_logs:
  prometheus-data:
  grafana-storage:
