version: '3.7'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      #      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      monitoring:
        aliases:
          - grafana

  node-exporter:
    image: prom/node-exporter
    networks:
      - monitoring
    ports:
      - 9100:9100

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:Postgres1@postgres:5432/aia_perf1?sslmode=disable"
#      DATA_SOURCE_NAME: "postgresql://postgres:Postgres1@postgres:5432/postgres?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/queries/queries.yaml"
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"
      PG_EXPORTER_EXCLUDE_DATABASES: "template0,template1"
      PG_EXPORTER_CONSTANT_LABELS: "cluster_name=local"
    volumes:
    - ./postgres-exporter/:/queries
    ports:
    - 9187:9187
    networks:
    - monitoring



  adminer:
    image: adminer
    restart: always
    ports:
      - '18080:8080'

  postgres:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_DB=aia_perf1
      - POSTGRES_PASSWORD=Postgres01
      - POSTGRES_USER=postgres
      - TZ=Europe/Kiev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    command:
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
      -c log_min_error_statement=error
      -c log_autovacuum_min_duration=0
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

volumes:
  postgres_data:
  postgres_logs:
  prometheus-data:
  grafana-storage: { }

networks:
  monitoring:


  #
  #  grafana:
  #    build: 'config/grafana'
  #    ports:
  #      - 3000:3000
  #    volumes:
  ##      - grafana-storage:/etc/grafana
  #      - ./grafana:/etc/grafana
  ##      - grafana-storage:/var/lib/grafana
  ##      - ./grafana:/var/lib/grafana
  #    environment:
  #      - GF_SECURITY_ADMIN_USER=admin
  #      - GF_SECURITY_ADMIN_PASSWORD=admin
  #    networks:
  #      monitoring:
  #        aliases:
  #          - grafana


  #  grafana:
  #    image: grafana/grafana:9.3.6
  #    ports:
  #      - 3000:3000
  #    depends_on:
  #      - prometheus
  #
  #    environment:
  #      - GF_SECURITY_ADMIN_USER=admin
  #      - GF_SECURITY_ADMIN_PASSWORD=admin
  #    volumes:
  #      - grafana-storage:/var/lib/grafana
  #


#docker-compose up --build
#docker-compose up --d