global:
  scrape_interval: 15s

scrape_configs:
#  -  job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9090']
  - job_name: 'spring-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
#      - targets: ['localhost:8080']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100

#  - job_name: 'postgresql'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9187']

          #default postgres importer port